version: "3.3"
services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: "symfony-api-test"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - "./private/var/lib/postgresql:/var/lib/postgresql"
  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - postgres
  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=symfony-api-test
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - postgres
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "8000:80"
    volumes:
      - "./public:/app/public"
    depends_on:
      - php-fpm
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./private/var/lib/mongodb:/data/db"
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongo