version: "3.7"
services:

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "8080:80"
    volumes:
      - "./public:/app/public"
    depends_on:
      - php-fpm

  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - postgres
      - mysql
      - elastic
      - mongo

  redis:
    container_name: redis
    hostname: redis
    restart: always
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6739:6739"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8083:8081"

  postgres:
    image: postgres
    restart: always
    volumes:
      - "./data/databases/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_zdravcity
    ports:
      - "5432:5432"

  adminer:
    build: ./images/adminer
    restart: always
    ports:
      - "8084:8080"
    environment:
      - ADMINER_DESIGN=price

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    restart: always
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic_password
    ports:
      - "9200:9200"
      - "9300:9300"

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "./data/databases/mongo:/var/lib/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/databases/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=zdravcity
      - MYSQL_PASSWORD=zdravcity
      - MYSQL_DATABASE=zdravcity